services:
  - type: web
    name: agripool-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
      - key: STELLAR_NETWORK
        value: TESTNET
      - key: STELLAR_HORIZON_URL
        value: https://horizon-testnet.stellar.org
      - key: SOROBAN_RPC_URL
        value: https://soroban-testnet.stellar.org
      - key: CONTRACT_ID
        sync: false
      - key: SOROBAN_READ_SOURCE_ACCOUNT
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: POSTHOG_API_KEY
        sync: false
